version: "3.1"
services:
  openemr:
    # The official image for 5.0.0 by openemr is horrible.
    # So, I build my own.
    # image: openemr/openemr:5.0.0
    build: openemr/
    env_file:
      - openemr/openemr.devpc.env
    labels:
      - traefik.frontend.rule=Host:openemr.example.com
      - traefik.port=80
      - traefik.enable=true
    volumes:
      # Line below is Just a place holder
      - ${PWD}/openemr/sqlconf.php:/tmp/sqlconf.php
      # Temporary hack - mount the file with real db passwords, etc inside the container.
      - ${PWD}/openemr/sqlconf.php:/var/www/html/sites/default/sqlconf.php
      # The persistent location for some openemr site-specific files
      # - /home/containers-data/openemr-sites:/var/www/localhost/htdocs/openemr/sites
      # Using volume with this container image is important,
      #   because it has some stuff in sites directory, 
      #   which can only be copied to persistent location, if that location is a docker volume.
      #   it should not be a host mounted directory.
      # - sitevolume:/var/www/localhost/htdocs/openemr/sites
    depends_on:
      - db
    networks:
      # This 'uses' the proxy network called 'services-network'
      - services-network

  db:
    # image: mariadb:10.4
    # For now, mysql:5.7 is a safe choice - for backward compatibility
    image: mysql:5.7
    env_file:
      - db/db.devpc.env
    volumes:
      - ${PWD}/db/conf.d:/etc/mysql/conf.d
      - ${PWD}/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - /home/containers-data/openemr-db:/var/lib/mysql
      - dbvolume:/var/lib/mysql
    networks:
      - services-network

  traefik:
    image: traefik:1.7
    labels:
      # Traefik does not need a PathPrefix
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.port=8080
      - traefik.enable=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/traefik.toml:/etc/traefik/traefik.toml
      # The password file is generated with command:- 
      #          "htpasswd -c -B traefik-dashboard-users.passwd  admin"
      # - ${PWD}/traefik/traefik-dashboard-users.passwd:/traefik-dashboard-users.passwd
      - ${PWD}/traefik/acme.json:/acme.json
      # note: acme.json need to have 0600 permissions.
    ports:
      - 80:80
      - 443:443
    networks:
      # This 'uses' the proxy network called 'services-network'
      - services-network

volumes:
  sitevolume: {}
  dbvolume: {}

networks:
  services-network:
    external: true
