# version 1.7
defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  domain = "example.com"
  network = "services-network"

# enabling api is not absolutely necessary, it is needed only if you need dashboard.
[api]
  dashboard = true
  entrypoint = "dashboard"

[entryPoints]
  [entryPoints.http]
  address = ":80"

# Enable the following two lines if you want automatic HTTPS redirection.
# Remember, that Traefik will issue self signed certificates if you are not using ACME.
# That should be alright, as you are running this on your local computer anyway.

#    [entryPoints.http.redirect]
#    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [entryPoints.dashboard]
  address = ":8080"
